// --- Directions
// Print out the n-th entry in the fibonacci series.
// The fibonacci series is an ordering of numbers where
// each number is the sum of the preceeding two.
// For example, the sequence
//  [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
// forms the first ten entries of the fibonacci series.
// Example:
//   fib(4) === 3

// Solution - iterative

// steps
// first two numbers can not effectively generated by a for loop
// begin with the result of our index 0 and index 1
// start the for loop at index 2
// to get the previous element i - 1
// get the second i - 2
// combine the results and push them to the result array
// return the nth ENTRY


// linear time
function fib(n) {

  let result = [0, 1];

  for (let i = 2; i <= n; i++) {
    let a = result[i - 1];
    let b = result[i - 2];

    result.push(a + b);
  }

  return result[n];
}



module.exports = fib;
